baseURL = "https://amazing-wing-48d861.netlify.com/"
languageCode = "id-id"
title = "MarketHerbal"
theme = "datarc"

[taxonomies]
tag = "tags"
category = "categories"

[outputs]
page = ["HTML", "AMP", "RSS"]

[params]
  logo = "/img/logo.png"
  
  brand_color = "rgba(91, 97, 207, 0.95)"
  second_color = "rgba(60, 64, 143, 0.95)"
